language: c

script:
  - cd testpkg
  - gzip .SRCINFO
  - cd ./..
  - cd build
  - tar -cf testpkg.pkg.tar -C ./../testpkg ./.PKGINFO ./.SRCINFO.gz ./tmp/test/testfile
  - gzip testpkg.pkg.tar
  - cmake ..
  - make
  - ./coldbrew install --local testpkg.pkg.tar.gz
  - ls /tmp/test
  - ./coldbrew uninstall testpkg
  - ls /tmp/
